### ISSUE TITLE
valve poll

### ISSUE THREAD

**Issue by AlexTransit** [temoto/vender#13]
api.go:39: debug: tele.Error: github.com/temoto/vender/hardware/mdb/evend/generic.go:94: evend.valve(c0) POLL=30 unexpected

отдает сдачу и отключается по ошибке

**Comment by temoto** [comment]
В ответе на опрос блока соленоидов неизвестный бит 0x20.

Задокументированы 0x10 льется вода и 0x40 горячая температура ушла от заданной.

30 это 10 льется вода + еще что-то.
