### ISSUE TITLE
mega packet (прилетает перед отключением. видимо отрубают потребителей (изо))

### ISSUE THREAD

**Issue by AlexTransit** [temoto/vender#14]
прилетает перед отключением. видимо отрубают потребителей (изо) 

mega-client stray packet OK clock10u=136400us,mdb_result=UART_READ_ERROR:00,mdb_duration=136280us,mdb_data= debug=440c0102354810110012353c110000

**Comment by temoto** [comment]
Это шум на меге UART RX. Должен помочь RC-фильтр.

**Comment by AlexTransit** [comment]
commit c2afac544652853ef6cc286406ef0dfb943cd7d8

**Comment by temoto** [comment]
@AlexTransit наверное, другой комит, он бы подсветился в ссылку.

**Comment by AlexTransit** [comment]
@temoto это я скопипастил из ```git log```
